### ISSUE TITLE
Añade datos a la excepción

### ISSUE THREAD

**Issue by lmagarin** [Markweell/Markweell.github.io#35]
https://github.com/Markweell/Markweell.github.io/blob/496a82e76d41030c265dd8c8e3090540c6c33bdd/1.Cliente/Tema7/BuscaminasConJQuery/js/buscaminas.js#L134

throw new Error("Enhorabuena, has ganado.");

let error = new Error("Enhorabuena, has ganado.");

error.i = i;
error.j = j;
error.de = i;
throw errror;

**Comment by lmagarin** [comment]
¿para qué ?

> error.de = i;

**Comment by Markweell** [comment]
No entiendo Lourdes, lo que he hecho para resolver este issue es guardar el array que genero de coordenadas picadas en el error. Cuando salta el error recojo e, array de coordenadas y las pico

**Comment by lmagarin** [comment]
Sí, pero la variable i ya la enviabas en 
error.i = i;
y también en 
error.de = i;
???
